const PDFDocument = require('pdfkit');

function formatDate(date) {
    if (!date) return '';
    const d = new Date(date);
    if (isNaN(d.getTime())) return String(date);
    const year = d.getFullYear();
    const month = String(d.getMonth() + 1).padStart(2, '0');
    const day = String(d.getDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
}

class AttendanceReportBuilder {
    constructor(analytics) {
        this.analytics = analytics;
        this.doc = new PDFDocument({
            size: 'A4',
            margins: { top: 40, bottom: 50, left: 45, right: 45 },
            autoFirstPage: true
        });

        // Colors
        this.C_PRIMARY = '#1e1b4b'; // Deep Indigo
        this.C_TEXT = '#1e293b';    // Slate 800
        this.C_MUTED = '#64748b';   // Slate 500
        this.C_ACCENT = '#7c3aed';  // Violet 600
        this.C_BORDER = '#e2e8f0';  // Slate 200
        this.C_BG_ROW = '#f8fafc';  // Slate 50

        // Status Colors mapping
        this.STATUS_COLORS = {
            'Present': '#10b981',       // Green
            'Absent': '#ef4444',        // Red
            'Medical Leave': '#3b82f6', // Blue
            'On Duty': '#8b5cf6',       // Purple
            'Cancelled': '#64748b',     // Grey
            'Holiday': '#fbbf24',       // Yellow
            'Exam': '#b91c1c',          // Dark Red
            'Event': '#0ea5e9',         // Sky Blue
            'Yet To Be Taken': '#94a3b8' // Light Grey
        };

        // Track pagination
        this.pageCount = 0;
        this.setupPageNumbering();
    }

    setupPageNumbering() {
        this.doc.on('pageAdded', () => {
            this.pageCount++;
        });
        // Initial page increment
        this.pageCount = 1;
    }

    drawFooter(pageIndex, totalPages) {
        this.doc.save();
        const y = 800;
        // Thin footer divider
        this.doc.strokeColor(this.C_BORDER).lineWidth(0.5).moveTo(45, y).lineTo(550, y).stroke();
        
        // Footer text
        this.doc.fillColor(this.C_MUTED).fontSize(8).font('Helvetica');
        this.doc.text('Generated by AskUrSenior', 45, y + 8);
        this.doc.text('Attendance Engine v3.0', 45, y + 20);
        
        const studentIdText = `Student ID: ${this.analytics.student.id}`;
        this.doc.text(studentIdText, 220, y + 8, { width: 150, align: 'center' });
        
        const pageText = `Page ${pageIndex} of ${totalPages}`;
        this.doc.text(pageText, 450, y + 8, { width: 100, align: 'right' });
        this.doc.restore();
    }

    drawHeader(title) {
        this.doc.save();
        this.doc.fillColor(this.C_PRIMARY).fontSize(16).font('Helvetica-Bold').text(title, 45, 45);
        this.doc.strokeColor(this.C_BORDER).lineWidth(1).moveTo(45, 65).lineTo(550, 65).stroke();
        this.doc.restore();
    }

    build() {
        return new Promise((resolve, reject) => {
            try {
                const chunks = [];
                this.doc.on('data', chunk => chunks.push(chunk));
                this.doc.on('end', () => {
                    const totalPages = this.pageCount;
                    // Let's resolve the buffer with page numbering applied
                    resolve(Buffer.concat(chunks));
                });
                this.doc.on('error', reject);

                // 1. Cover Section
                this.buildCoverSection();

                // 2. Overall Dashboard (Summary)
                this.doc.addPage();
                this.buildOverallSummarySection();

                // 3. Subject Summaries Section
                this.doc.addPage();
                this.buildSubjectSummarySection();

                // 4. Analytics Section (Monthly & Highlights)
                this.doc.addPage();
                this.buildAnalyticsSection();

                // 5. Calendar Events Timeline
                this.doc.addPage();
                this.buildEventTimelineSection();

                // 6. Legend Page
                this.doc.addPage();
                this.buildAttendanceLegendSection();

                // 7. Subject-wise grouped timelines
                this.buildSubjectTimelinesSection();

                this.doc.end();
            } catch (err) {
                reject(err);
            }
        });
    }

    buildCoverSection() {
        // Decorative background shapes
        this.doc.save();
        this.doc.rect(0, 0, 595, 20).fill(this.C_PRIMARY);
        this.doc.rect(0, 20, 595, 5).fill(this.C_ACCENT);
        
        // Large title text
        this.doc.fillColor(this.C_PRIMARY).fontSize(34).font('Helvetica-Bold').text('AskUrSenior', 80, 220);
        this.doc.fillColor(this.C_ACCENT).fontSize(20).font('Helvetica-Bold').text('ACADEMIC ATTENDANCE ENGINE REPORT', 80, 265);
        this.doc.fillColor(this.C_MUTED).fontSize(11).font('Helvetica').text('Official Semester Record & Analytics Planner', 80, 290);
        
        this.doc.rect(80, 320, 435, 1.5).fill(this.C_BORDER);

        // Student Info Box
        let y = 350;
        const student = this.analytics.student;
        const rows = [
            ['Student Name', student.name],
            ['University Seat No (USN)', student.usn],
            ['College', student.college],
            ['Branch / Department', student.branch],
            ['Academic Scheme', student.scheme],
            ['Semester & Year', `Semester ${student.semester}  |  Academic Year ${student.academicYear}`],
            ['Report Version', `${this.analytics.metadata.reportVersion}  (Engine v${this.analytics.metadata.engineVersion})`],
            ['Generated On', new Date(this.analytics.metadata.generatedOn).toLocaleString('en-GB')]
        ];

        rows.forEach(([label, val]) => {
            this.doc.fillColor(this.C_MUTED).fontSize(10).font('Helvetica').text(label, 80, y, { width: 160 });
            this.doc.fillColor(this.C_TEXT).fontSize(11).font('Helvetica-Bold').text(val || 'N/A', 250, y, { width: 280 });
            y += 26;
        });

        // Verifiable QR Section placeholder info
        this.doc.rect(80, 600, 435, 80).strokeColor(this.C_BORDER).lineWidth(0.5).stroke();
        this.doc.fillColor(this.C_PRIMARY).fontSize(9).font('Helvetica-Bold').text('SECURE VERIFICATION QR CODE', 95, 612);
        this.doc.fillColor(this.C_MUTED).fontSize(8).font('Helvetica').text('This document is compiled dynamically from the student\'s verified timetable, personal event calendars, registered class selections, and attendance entries. To verify, scan the QR code using AskUrSenior Academic Verification scanner.', 95, 628, { width: 400 });

        this.doc.restore();
    }

    buildOverallSummarySection() {
        this.drawHeader('Overall Attendance Dashboard');
        
        // Statistics Grid
        const stats = this.analytics.overall;
        
        // Attendance Percent box
        this.doc.save();
        this.doc.rect(45, 85, 240, 95).fill('#faf5ff');
        this.doc.rect(45, 85, 240, 95).strokeColor(this.C_ACCENT).lineWidth(0.5).stroke();
        this.doc.fillColor(this.C_ACCENT).fontSize(11).font('Helvetica-Bold').text('OVERALL ATTENDANCE RATE', 65, 100);
        this.doc.fillColor(this.C_PRIMARY).fontSize(36).font('Helvetica-Bold').text(`${stats.attendance}%`, 65, 120);
        
        let healthLabel = stats.healthStatus;
        this.doc.fillColor(this.C_TEXT).fontSize(9).font('Helvetica-Bold').text(`Cushion Status: `, 65, 160);
        this.doc.text(healthLabel, 138, 160);
        this.doc.restore();

        // Target cushion / streaks details
        this.doc.save();
        this.doc.rect(300, 85, 250, 95).fill('#f8fafc');
        this.doc.rect(300, 85, 250, 95).strokeColor(this.C_BORDER).lineWidth(0.5).stroke();
        
        this.doc.fillColor(this.C_MUTED).fontSize(9).font('Helvetica-Bold').text('STREAKS', 315, 98);
        this.doc.fillColor(this.C_TEXT).fontSize(10).font('Helvetica').text(`Current Present Streak: `, 315, 114);
        this.doc.font('Helvetica-Bold').text(`${stats.streak.current} classes`, 430, 114);
        this.doc.font('Helvetica').text(`Longest Present Streak: `, 315, 130);
        this.doc.font('Helvetica-Bold').text(`${stats.streak.longest} classes`, 430, 130);
        
        this.doc.fillColor(this.C_MUTED).fontSize(9).font('Helvetica-Bold').text('CUSHION PLAN', 315, 150);
        if (stats.attendance >= 85) {
            this.doc.fillColor(this.C_TEXT).fontSize(10).font('Helvetica').text(`Safe to miss up to: `, 315, 164);
            this.doc.fillColor('#10b981').font('Helvetica-Bold').text(`${stats.canMiss} classes`, 415, 164);
        } else {
            this.doc.fillColor(this.C_TEXT).fontSize(10).font('Helvetica').text(`Must attend next: `, 315, 164);
            this.doc.fillColor('#ef4444').font('Helvetica-Bold').text(`${stats.needToAttend} classes`, 410, 164);
        }
        this.doc.restore();

        // Semester progress
        let y = 205;
        this.doc.fillColor(this.C_PRIMARY).fontSize(11).font('Helvetica-Bold').text('SEMESTER PROGRESS', 45, y);
        this.doc.fillColor(this.C_MUTED).fontSize(9).font('Helvetica').text(`${stats.completedDays} days completed  |  ${stats.remainingDays} days remaining`, 350, y, { align: 'right', width: 200 });
        
        // Progress bar background
        this.doc.save();
        this.doc.rect(45, y + 16, 505, 10).fill('#e2e8f0');
        const progressWidth = Math.min(505, (stats.semesterProgressPct / 100) * 505);
        this.doc.rect(45, y + 16, progressWidth, 10).fill(this.C_ACCENT);
        this.doc.restore();
        this.doc.fillColor(this.C_PRIMARY).fontSize(9).font('Helvetica-Bold').text(`${stats.semesterProgressPct}% Completed`, 45, y + 32);

        // Core numbers blocks (Expected, Conducted, Present, Absent, Medical Leave, Cancelled)
        y = 265;
        this.doc.fillColor(this.C_PRIMARY).fontSize(11).font('Helvetica-Bold').text('SEMESTER CLASS METRICS', 45, y);
        
        const metricCols = [
            ['Expected', stats.expected],
            ['Conducted', stats.conducted],
            ['Present', stats.present],
            ['Absent', stats.absent],
            ['Medical', stats.medicalLeave],
            ['Cancelled', stats.cancelled]
        ];

        let x = 45;
        metricCols.forEach(([lbl, val]) => {
            this.doc.save();
            this.doc.rect(x, y + 16, 76, 50).fill('#f8fafc');
            this.doc.rect(x, y + 16, 76, 50).strokeColor(this.C_BORDER).lineWidth(0.5).stroke();
            this.doc.fillColor(this.C_MUTED).fontSize(8).font('Helvetica').text(lbl.toUpperCase(), x + 5, y + 24, { width: 66, align: 'center' });
            this.doc.fillColor(this.C_PRIMARY).fontSize(14).font('Helvetica-Bold').text(String(val), x + 5, y + 42, { width: 66, align: 'center' });
            this.doc.restore();
            x += 86;
        });

        // Future predictions
        y = 350;
        this.doc.fillColor(this.C_PRIMARY).fontSize(11).font('Helvetica-Bold').text('ATTENDANCE DYNAMIC PREDICTIONS', 45, y);
        
        const predictions = [
            ['If you attend every remaining class', `${stats.predictions.ifAttendAll}%`, 'Maximum reachable percentage this semester.'],
            ['If you miss next 3 classes', `${stats.predictions.ifMissNext3}%`, 'Estimated percentage if you miss 3 future classes.'],
            ['If you miss next 5 classes', `${stats.predictions.ifMissNext5}%`, 'Estimated percentage if you miss 5 future classes.']
        ];

        let predY = y + 18;
        predictions.forEach(([title, val, desc]) => {
            this.doc.save();
            this.doc.rect(45, predY, 505, 36).strokeColor(this.C_BORDER).lineWidth(0.5).stroke();
            this.doc.fillColor(this.C_TEXT).fontSize(10).font('Helvetica-Bold').text(title, 60, predY + 8);
            this.doc.fillColor(this.C_MUTED).fontSize(8).font('Helvetica').text(desc, 60, predY + 20);
            
            const isDanger = parseFloat(val) < 85;
            this.doc.fillColor(isDanger ? '#ef4444' : '#10b981').fontSize(12).font('Helvetica-Bold').text(val, 470, predY + 12, { align: 'right', width: 65 });
            this.doc.restore();
            predY += 46;
        });

        this.drawFooter(2, this.pageCount);
    }

    buildSubjectSummarySection() {
        this.drawHeader('Subject-wise Summary');

        let y = 80;
        this.analytics.subjects.forEach((s) => {
            if (y > 700) {
                this.drawFooter(this.pageCount, this.pageCount); // wait, footer rendering logic uses placeholder, but drawing page number is fine
                this.doc.addPage();
                this.drawHeader('Subject-wise Summary (Contd.)');
                y = 80;
            }

            this.doc.save();
            // Subject container box
            this.doc.rect(45, y, 505, 78).strokeColor(this.C_BORDER).lineWidth(0.5).stroke();
            
            // Left: Name, Code & category
            this.doc.fillColor(this.C_TEXT).fontSize(11).font('Helvetica-Bold').text(s.name, 60, y + 10, { width: 280, ellipsis: true });
            this.doc.fillColor(this.C_MUTED).fontSize(8.5).font('Helvetica').text(`${s.code}  |  ${s.category}  |  ${s.credits} Credits`, 60, y + 25);
            
            // Present bar graph
            this.doc.rect(60, y + 42, 260, 6).fill('#e2e8f0');
            const progressVal = Math.min(260, (s.attendancePercentage / 100) * 260);
            const progressColor = s.attendancePercentage >= 90 ? '#10b981' : (s.attendancePercentage >= 85 ? '#fbbf24' : '#ef4444');
            this.doc.rect(60, y + 42, progressVal, 6).fill(progressColor);
            
            // Present/Conducted label
            this.doc.fillColor(this.C_MUTED).fontSize(8.5).font('Helvetica').text(`${s.analytics.present} / ${s.analytics.conducted} Conducted  (Exp ${s.analytics.expected})`, 60, y + 54);

            // Right column: Streaks, cushion and health status
            this.doc.fillColor(s.attendancePercentage >= 85 ? '#10b981' : '#ef4444').fontSize(14).font('Helvetica-Bold').text(`${s.attendancePercentage}%`, 450, y + 10, { width: 85, align: 'right' });
            
            const healthStatus = s.analytics.healthStatus;
            this.doc.fillColor(this.C_TEXT).fontSize(9).font('Helvetica').text(`Status: `, 360, y + 12);
            this.doc.font('Helvetica-Bold').text(healthStatus, 395, y + 12);

            this.doc.font('Helvetica').fillColor(this.C_MUTED).text(`Current Streak: `, 360, y + 28);
            this.doc.font('Helvetica-Bold').text(`🔥 ${s.analytics.streak.current}`, 430, y + 28);

            this.doc.font('Helvetica').fillColor(this.C_MUTED).text(`Longest Streak: `, 360, y + 42);
            this.doc.font('Helvetica-Bold').text(`${s.analytics.streak.longest}`, 430, y + 42);

            this.doc.font('Helvetica').fillColor(this.C_MUTED).text(s.attendancePercentage >= 85 ? 'Can Miss: ' : 'Need Attend: ', 360, y + 56);
            this.doc.font('Helvetica-Bold').fillColor(s.attendancePercentage >= 85 ? '#10b981' : '#ef4444').text(s.attendancePercentage >= 85 ? `${s.analytics.canMiss} classes` : `${s.analytics.needToAttend} classes`, 430, y + 56);

            this.doc.restore();
            y += 92;
        });

        this.drawFooter(3, this.pageCount);
    }

    buildAnalyticsSection() {
        this.drawHeader('Monthly & Semester Analytics');

        // Semester Analytics Highlights
        let y = 80;
        this.doc.fillColor(this.C_PRIMARY).fontSize(11).font('Helvetica-Bold').text('SEMESTER PERFORMANCE HIGHLIGHTS', 45, y);
        
        const highlights = this.analytics.semesterAnalytics;
        const grid = [
            ['Best Subject', highlights.bestSubject ? `${highlights.bestSubject.name} (${highlights.bestSubject.pct}%)` : 'N/A'],
            ['Lowest Subject', highlights.lowestSubject ? `${highlights.lowestSubject.name} (${highlights.lowestSubject.pct}%)` : 'N/A'],
            ['Most Missed Subject', highlights.mostMissedSubject ? `${highlights.mostMissedSubject.name} (${highlights.mostMissedSubject.absentCount} absent)` : 'N/A'],
            ['Highest Attendance Streak', highlights.highestStreakSubject ? `${highlights.highestStreakSubject.name} (${highlights.highestStreakSubject.streak} classes)` : 'N/A'],
            ['Longest Absence Streak', `${highlights.longestAbsence} classes`],
            ['Total Scheduled Holidays', `${highlights.totalHolidays} days`],
            ['Total Exams & CIE Conducted', `${highlights.totalExams} sessions`],
            ['Total Festivals & Events', `${highlights.totalEvents} events`],
            ['Semester Completion Rate', `${highlights.semesterCompletionPct}% Completed`]
        ];

        y += 18;
        grid.forEach(([lbl, val]) => {
            this.doc.fillColor(this.C_MUTED).fontSize(9.5).font('Helvetica').text(lbl, 60, y);
            this.doc.fillColor(this.C_TEXT).fontSize(10).font('Helvetica-Bold').text(val, 280, y, { width: 250 });
            y += 24;
            // Divider line
            this.doc.save().strokeColor(this.C_BORDER).lineWidth(0.5).moveTo(60, y - 4).lineTo(530, y - 4).stroke().restore();
        });

        // Monthly Analytics Grid
        y += 15;
        this.doc.fillColor(this.C_PRIMARY).fontSize(11).font('Helvetica-Bold').text('MONTHLY ATTENDANCE GRID', 45, y);
        
        y += 20;
        // Table Header
        this.doc.save();
        this.doc.fillColor(this.C_PRIMARY).fontSize(8.5).font('Helvetica-Bold');
        this.doc.text('Month', 50, y);
        this.doc.text('Expected', 200, y);
        this.doc.text('Conducted', 280, y);
        this.doc.text('Present', 360, y);
        this.doc.text('Attendance Rate', 440, y);
        this.doc.restore();
        
        y += 14;
        this.doc.strokeColor(this.C_PRIMARY).lineWidth(1).moveTo(45, y).lineTo(550, y).stroke();
        y += 4;

        this.analytics.monthlyAnalytics.forEach((m, idx) => {
            if (idx % 2 === 0) {
                this.doc.save().rect(45, y - 2, 505, 18).fill(this.C_BG_ROW).restore();
            }
            this.doc.fillColor(this.C_TEXT).fontSize(9).font('Helvetica').text(m.month, 50, y);
            this.doc.text(String(m.expected), 200, y);
            this.doc.text(String(m.conducted), 280, y);
            this.doc.text(String(m.present), 360, y);
            
            const color = m.attendancePercentage >= 85 ? '#10b981' : '#ef4444';
            this.doc.save().fillColor(color).font('Helvetica-Bold').text(`${m.attendancePercentage}%`, 440, y).restore();
            
            y += 18;
        });

        this.drawFooter(4, this.pageCount);
    }

    buildEventTimelineSection() {
        this.drawHeader('Event & Holiday Calendar');

        let y = 80;
        this.doc.fillColor(this.C_MUTED).fontSize(9.5).font('Helvetica').text('Timeline of academic holidays, CIE test cycles, and campus events intersecting class cancellations:', 45, y);
        
        y += 24;
        this.doc.save();
        this.doc.fillColor(this.C_PRIMARY).fontSize(8.5).font('Helvetica-Bold');
        this.doc.text('Date', 50, y);
        this.doc.text('Event Title / Description', 140, y);
        this.doc.text('Type', 360, y);
        this.doc.text('Classes Suspended', 450, y);
        this.doc.restore();

        y += 14;
        this.doc.strokeColor(this.C_PRIMARY).lineWidth(1).moveTo(45, y).lineTo(550, y).stroke();
        y += 4;

        // Collect merged events
        const mergedEvents = [];
        this.analytics.eventsList.forEach(e => {
            const dStart = new Date(e.startDate);
            const dEnd = new Date(e.endDate);
            const startStr = dStart.toLocaleDateString('en-GB', { day: '2-digit', month: 'short' });
            const endStr = dEnd.toLocaleDateString('en-GB', { day: '2-digit', month: 'short' });
            const dateStr = startStr === endStr ? startStr : `${startStr} - ${endStr}`;
            
            let suspended = 'No';
            if (e.classesSuspended) {
                if (e.suspensionType === 'full_day') {
                    suspended = 'Yes (All Day)';
                } else if (e.suspensionType === 'time_range') {
                    suspended = 'Yes (Partial)';
                }
            }

            mergedEvents.push({
                date: dateStr,
                sortBy: e.startDate,
                title: e.title,
                type: e.eventType,
                suspended
            });
        });

        // Sort ascending
        mergedEvents.sort((a, b) => new Date(a.sortBy) - new Date(b.sortBy));

        if (mergedEvents.length === 0) {
            this.doc.fillColor(this.C_MUTED).fontSize(10).font('Helvetica').text('No events or holidays registered for this semester duration.', 50, y + 20);
        } else {
            mergedEvents.forEach((ev, idx) => {
                if (y > 720) {
                    this.drawFooter(this.pageCount, this.pageCount);
                    this.doc.addPage();
                    this.drawHeader('Event & Holiday Calendar (Contd.)');
                    y = 80;
                }

                if (idx % 2 === 0) {
                    this.doc.save().rect(45, y - 2, 505, 18).fill(this.C_BG_ROW).restore();
                }

                this.doc.fillColor(this.C_TEXT).fontSize(9).font('Helvetica');
                
                const dFormatted = ev.date;
                this.doc.text(dFormatted, 50, y);
                this.doc.text(ev.title, 140, y, { width: 210, ellipsis: true });
                this.doc.text(ev.type, 360, y);
                
                const suspColor = ev.suspended.includes('Yes') ? '#ef4444' : '#64748b';
                this.doc.save().fillColor(suspColor).font('Helvetica-Bold').text(ev.suspended, 450, y).restore();

                y += 18;
            });
        }

        this.drawFooter(5, this.pageCount);
    }

    buildAttendanceLegendSection() {
        this.drawHeader('Attendance Status Legend');

        let y = 100;
        this.doc.fillColor(this.C_PRIMARY).fontSize(13).font('Helvetica-Bold').text('Attendance Status Identifiers & Page Codes', 50, y);
        this.doc.rect(50, y + 16, 495, 1).fill(this.C_BORDER);

        const legends = [
            ['✓ Present', 'Present', 'Class conducted and student was present.'],
            ['✕ Absent', 'Absent', 'Class conducted and student was absent.'],
            ['⚕ Medical Leave', 'Medical Leave', 'Student was absent due to approved medical reasons. Excused.'],
            ['🏫 On Duty', 'On Duty', 'Student was participating in college-sanctioned events (OD). Considered present.'],
            ['🚫 Cancelled', 'Cancelled', 'Class cancelled by faculty. Exempted from expected classes count.'],
            ['🟡 Holiday', 'Holiday', 'Official national or state holiday. No classes expected.'],
            ['🔴 Exam / CIE', 'Exam', 'Internal examinations or continuous evaluation tests conducted.'],
            ['🔵 Festival / Event', 'Event', 'Campus fest, athletic event, or cultural meet.'],
            ['○ Yet To Be Taken', 'Yet To Be Taken', 'Future scheduled class. Attendance decision pending. Planner placeholder.']
        ];

        y += 36;
        legends.forEach(([icon, label, description]) => {
            this.doc.save();
            const color = this.STATUS_COLORS[label] || this.C_TEXT;
            
            // Draw status badge icon
            this.doc.fillColor(color).fontSize(11).font('Helvetica-Bold').text(icon, 70, y, { width: 110 });
            this.doc.fillColor(this.C_TEXT).fontSize(9.5).font('Helvetica-Bold').text(label, 190, y);
            this.doc.fillColor(this.C_MUTED).fontSize(9).font('Helvetica').text(description, 290, y, { width: 230 });
            
            this.doc.restore();
            y += 36;
        });

        this.drawFooter(6, this.pageCount);
    }

    buildSubjectTimelinesSection() {
        // Timeline filtering options can be processed here
        this.analytics.subjects.forEach((s) => {
            this.doc.addPage();
            this.drawHeader(`${s.name} - Detailed Timeline`);

            const subjectIdStr = s.subjectId.toString();
            // Filter global grouped timeline for this subject
            const subjGroupedTimeline = this.analytics.groupedTimeline.map(group => {
                const subjSlots = group.slots.filter(sl => sl.subject.toString() === subjectIdStr);
                return {
                    ...group,
                    slots: subjSlots
                };
            }).filter(group => group.slots.length > 0);

            let y = 85;
            // Draw Subject mini metrics summary header
            this.doc.save();
            this.doc.rect(45, y, 505, 45).fill('#f8fafc');
            this.doc.rect(45, y, 505, 45).strokeColor(this.C_BORDER).lineWidth(0.5).stroke();
            
            this.doc.fillColor(this.C_MUTED).fontSize(8.5).font('Helvetica-Bold').text('EXPECTED', 60, y + 10);
            this.doc.fillColor(this.C_TEXT).fontSize(11).font('Helvetica-Bold').text(String(s.analytics.expected), 60, y + 24);

            this.doc.fillColor(this.C_MUTED).fontSize(8.5).font('Helvetica-Bold').text('CONDUCTED', 130, y + 10);
            this.doc.fillColor(this.C_TEXT).fontSize(11).font('Helvetica-Bold').text(String(s.analytics.conducted), 130, y + 24);

            this.doc.fillColor(this.C_MUTED).fontSize(8.5).font('Helvetica-Bold').text('PRESENT', 215, y + 10);
            this.doc.fillColor(this.C_TEXT).fontSize(11).font('Helvetica-Bold').text(String(s.analytics.present), 215, y + 24);

            this.doc.fillColor(this.C_MUTED).fontSize(8.5).font('Helvetica-Bold').text('ABSENT', 285, y + 10);
            this.doc.fillColor(this.C_TEXT).fontSize(11).font('Helvetica-Bold').text(String(s.analytics.absent), 285, y + 24);

            this.doc.fillColor(this.C_MUTED).fontSize(8.5).font('Helvetica-Bold').text('ATTENDANCE', 355, y + 10);
            this.doc.fillColor(s.attendancePercentage >= 85 ? '#10b981' : '#ef4444').fontSize(11).font('Helvetica-Bold').text(`${s.attendancePercentage}%`, 355, y + 24);

            this.doc.fillColor(this.C_MUTED).fontSize(8.5).font('Helvetica-Bold').text('CUSHION STATUS', 450, y + 10);
            this.doc.fillColor(s.attendancePercentage >= 85 ? '#10b981' : '#ef4444').fontSize(10).font('Helvetica-Bold').text(s.analytics.healthStatus, 450, y + 24);

            this.doc.restore();

            y += 65;
            this.doc.fillColor(this.C_PRIMARY).fontSize(10.5).font('Helvetica-Bold').text('CLASS TIMELINE INDEX', 45, y);
            y += 18;

            if (subjGroupedTimeline.length === 0) {
                this.doc.fillColor(this.C_MUTED).fontSize(10).font('Helvetica').text('No expected classes timeline log generated for this subject.', 50, y + 15);
            } else {
                subjGroupedTimeline.forEach((group) => {
                    if (y > 700) {
                        this.drawFooter(this.pageCount, this.pageCount);
                        this.doc.addPage();
                        this.drawHeader(`${s.name} - Detailed Timeline (Contd.)`);
                        y = 80;
                    }

                    // Group header (Date Box)
                    this.doc.save();
                    this.doc.rect(45, y, 505, 18).fill('#f1f5f9');
                    this.doc.fillColor(this.C_PRIMARY).fontSize(8.5).font('Helvetica-Bold').text(`${group.dayName.toUpperCase()},  ${group.formattedDate}`, 55, y + 5);
                    this.doc.fillColor(this.C_MUTED).fontSize(7.5).font('Helvetica').text(`Expected: ${group.expectedClasses}  |  Present: ${group.present}  |  Absent: ${group.absent}`, 370, y + 5, { width: 170, align: 'right' });
                    this.doc.restore();
                    y += 22;

                    group.slots.forEach((slot) => {
                        if (y > 730) {
                            this.drawFooter(this.pageCount, this.pageCount);
                            this.doc.addPage();
                            this.drawHeader(`${s.name} - Detailed Timeline (Contd.)`);
                            y = 80;
                        }

                        this.doc.save();
                        // Slot line details
                        this.doc.fillColor(this.C_TEXT).fontSize(9).font('Helvetica-Bold').text(slot.timeSlot || 'Anytime', 55, y);
                        
                        // Truncated subject name to prevent wrapping overlap
                        const trimmedSubj = s.name.length > 28 ? s.name.substring(0, 25) + '...' : s.name;
                        this.doc.fillColor(this.C_TEXT).font('Helvetica').text(trimmedSubj, 150, y, { width: 170 });
                        this.doc.fillColor(this.C_MUTED).fontSize(8).text(slot.lectureType || 'Lecture', 330, y);

                        const color = this.STATUS_COLORS[slot.status] || this.C_TEXT;
                        this.doc.fillColor(color).fontSize(9).font('Helvetica-Bold').text(slot.status, 390, y);

                        const remarkTxt = slot.remarks ? `(${slot.remarks})` : '-';
                        this.doc.fillColor(this.C_MUTED).font('Helvetica').fontSize(8).text(remarkTxt, 480, y, { width: 65, ellipsis: true });

                        this.doc.restore();
                        y += 18;
                    });
                    y += 6; // spacing after day group
                });
            }

            this.drawFooter(this.pageCount, this.pageCount);
        });
    }
}

module.exports = AttendanceReportBuilder;
