const pdfmake = require('pdfmake');

const fonts = {
    Helvetica: {
        normal: 'Helvetica',
        bold: 'Helvetica-Bold',
        italics: 'Helvetica-Oblique',
        bolditalics: 'Helvetica-BoldOblique'
    }
};

pdfmake.setFonts(fonts);

function formatDateTime(date) {
    if (!date) return '';
    const d = new Date(date);
    if (isNaN(d)) return '';
    const datePart = d.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
    const timePart = d.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', hour12: true });
    return `${datePart}, ${timePart}`;
}

exports.generateUsersReportPDF = (reportData) => {
    return new Promise((resolve, reject) => {
        try {
            const rangeStr = reportData.fromDate && reportData.toDate 
                ? `${reportData.fromDate.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })} -> ${reportData.toDate.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })}`
                : 'All Time';

            let mostRecentUserStr = 'N/A';
            if (reportData.users && reportData.users.length > 0) {
                const mostRecent = reportData.users.reduce((latest, current) => {
                    if (!current.lastActiveAt) return latest;
                    if (!latest || !latest.lastActiveAt) return current;
                    return new Date(current.lastActiveAt) > new Date(latest.lastActiveAt) ? current : latest;
                }, null);
                if (mostRecent) {
                    mostRecentUserStr = `${mostRecent.name || 'Anonymous'} (${formatDateTime(mostRecent.lastActiveAt)})`;
                }
            }

            const content = [];

            // Page 1: Cover Page
            content.push({ text: 'ASKURSENIOR', style: 'coverTitle', alignment: 'center', margin: [0, 60, 0, 10] });
            content.push({ text: 'USERS REPORT', style: 'coverSubtitle', alignment: 'center', margin: [0, 0, 0, 40] });

            content.push({
                columns: [
                    { width: '*', text: '' },
                    {
                        width: 'auto',
                        table: {
                            body: [
                                [{ text: 'Generated At:', style: 'infoLabel' }, { text: formatDateTime(reportData.generatedAt), style: 'infoValue' }],
                                [{ text: 'Report Range:', style: 'infoLabel' }, { text: rangeStr, style: 'infoValue' }],
                                [{ text: 'Generated By:', style: 'infoLabel' }, { text: 'AskUrSenior Admin Panel', style: 'infoValue' }],
                                [{ text: 'Total Users In Report:', style: 'infoLabel' }, { text: (reportData.summary.totalUsers || 0).toString(), style: 'infoValue' }]
                            ]
                        },
                        layout: 'noBorders'
                    },
                    { width: '*', text: '' }
                ],
                margin: [0, 0, 0, 60]
            });

            content.push({ text: 'SUMMARY', style: 'sectionTitle', alignment: 'center', margin: [0, 0, 0, 20] });
            
            content.push({
                columns: [
                    { width: '*', text: '' },
                    {
                        width: 'auto',
                        table: {
                            body: [
                                [{ text: 'Total Users', style: 'metricLabel' }, { text: (reportData.summary.totalUsers || 0).toString(), style: 'metricValue' }],
                                [{ text: 'Most Recently Active', style: 'metricLabel' }, { text: mostRecentUserStr, style: 'metricValue' }],
                                [{ text: 'Avg Unique Tabs', style: 'metricLabel' }, { text: (reportData.summary.averageTabsPerUser || 0).toString(), style: 'metricValue' }],
                                [{ text: 'Total Unique Tabs', style: 'metricLabel' }, { text: (reportData.summary.totalUniqueTabsVisited || 0).toString(), style: 'metricValue' }]
                            ]
                        },
                        layout: {
                            hLineWidth: function() { return 1; },
                            vLineWidth: function() { return 0; },
                            hLineColor: function() { return '#e2e8f0'; },
                            paddingTop: function() { return 12; },
                            paddingBottom: function() { return 12; }
                        }
                    },
                    { width: '*', text: '' }
                ]
            });

            // Page 2+: Table
            if (reportData.users.length === 0) {
                content.push({ text: 'No users found for the selected date range.', style: 'emptyState', alignment: 'center', pageBreak: 'before', margin: [0, 100, 0, 0] });
            } else {
                const tableBody = [];
                tableBody.push([
                    { text: 'Name', style: 'tableHeader' },
                    { text: 'USN', style: 'tableHeader' },
                    { text: 'Email', style: 'tableHeader' },
                    { text: 'Joined Date & Time', style: 'tableHeader' },
                    { text: 'Last Active Date & Time', style: 'tableHeader' },
                    { text: 'Unique Tabs', style: 'tableHeader', alignment: 'right' }
                ]);

                reportData.users.forEach(u => {
                    tableBody.push([
                        { text: (u.name || 'Anonymous').substring(0, 25), style: 'tableCell' },
                        { text: (u.usn || 'N/A').substring(0, 12), style: 'tableCell' },
                        { text: (u.email || ''), style: 'tableCellEmail' },
                        { text: formatDateTime(u.createdAt), style: 'tableCell' },
                        { text: formatDateTime(u.lastActiveAt), style: 'tableCell' },
                        { text: (u.uniqueTabsVisited || 0).toString(), style: 'tableCell', alignment: 'right' }
                    ]);
                });

                content.push({
                    pageBreak: 'before',
                    table: {
                        headerRows: 1,
                        widths: ['auto', 'auto', '*', 'auto', 'auto', 'auto'],
                        body: tableBody
                    },
                    layout: {
                        fillColor: function (rowIndex) {
                            if (rowIndex === 0) return '#1e293b'; 
                            return (rowIndex % 2 === 0) ? '#f8fafc' : '#ffffff'; 
                        },
                        hLineWidth: function (i, node) {
                            return (i === 0 || i === node.table.body.length) ? 0 : 1;
                        },
                        vLineWidth: function () { return 0; },
                        hLineColor: function () { return '#e2e8f0'; },
                        paddingLeft: function(i) { return 10; },
                        paddingRight: function(i) { return 10; },
                        paddingTop: function(i) { return 10; },
                        paddingBottom: function(i) { return 10; }
                    }
                });
            }

            const docDefinition = {
                pageSize: 'A4',
                pageOrientation: 'landscape',
                pageMargins: [40, 80, 40, 60],
                defaultStyle: { font: 'Helvetica', fontSize: 10, color: '#334155' },
                header: function(currentPage) {
                    if (currentPage > 1) {
                        return { text: 'ASKURSENIOR', margin: [40, 30, 40, 0], fontSize: 12, bold: true, color: '#94a3b8', alignment: 'right' };
                    }
                    return null;
                },
                footer: function(currentPage, pageCount) {
                    return {
                        columns: [
                            { text: 'Generated by AskUrSenior Admin Panel', alignment: 'left', color: '#94a3b8', fontSize: 9 },
                            { text: `Page ${currentPage} of ${pageCount}`, alignment: 'right', color: '#94a3b8', fontSize: 9 }
                        ],
                        margin: [40, 20, 40, 0]
                    };
                },
                content: content,
                styles: {
                    coverTitle: { fontSize: 32, bold: true, color: '#0f172a', letterSpacing: 2 },
                    coverSubtitle: { fontSize: 18, color: '#64748b', letterSpacing: 1 },
                    infoLabel: { fontSize: 11, color: '#64748b', bold: true, alignment: 'right', margin: [0, 4, 10, 4] },
                    infoValue: { fontSize: 11, color: '#0f172a', margin: [0, 4, 0, 4] },
                    sectionTitle: { fontSize: 14, bold: true, color: '#0f172a', letterSpacing: 1 },
                    metricLabel: { fontSize: 12, color: '#64748b', margin: [0, 0, 40, 0] },
                    metricValue: { fontSize: 12, color: '#0f172a', bold: true, alignment: 'right' },
                    tableHeader: { fontSize: 10, bold: true, color: '#ffffff' },
                    tableCell: { fontSize: 10, color: '#334155', margin: [0, 2] },
                    tableCellEmail: { fontSize: 10, color: '#0284c7', margin: [0, 2] },
                    emptyState: { fontSize: 14, color: '#94a3b8', italics: true }
                }
            };

            const doc = pdfmake.createPdf(docDefinition);
            
            doc.getBuffer()
                .then(buffer => resolve(buffer))
                .catch(err => reject(err));
        } catch (error) {
            reject(error);
        }
    });
};
