const PDFDocument = require('pdfkit');

// ---------- helpers ----------
function formatDateTime(date) {
    if (!date) return 'N/A';
    const d = new Date(date);
    if (isNaN(d)) return 'N/A';
    const datePart = d.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
    const timePart = d.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', hour12: true });
    return `${datePart}, ${timePart}`;
}

function formatDate(date) {
    if (!date) return 'N/A';
    const d = new Date(date);
    if (isNaN(d)) return 'N/A';
    return d.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
}

// Hex → [r,g,b]
function hex(h) {
    const n = parseInt(h.replace('#', ''), 16);
    return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
}

// ---------- constants ----------
const PAGE_W = 841.89; // A4 landscape width  (pt)
const PAGE_H = 595.28; // A4 landscape height (pt)
const MARGIN = 40;
const CONTENT_W = PAGE_W - MARGIN * 2;
const COL_WIDTHS = [130, 90, 180, 135, 135, 70]; // Name USN Email Joined LastActive Tabs

const C_NAVY   = hex('#0f172a');
const C_SLATE  = hex('#334155');
const C_MUTED  = hex('#64748b');
const C_LIGHT  = hex('#94a3b8');
const C_HEADER = hex('#1e293b');
const C_BLUE   = hex('#0284c7');
const C_ROW_A  = hex('#f8fafc');
const C_WHITE  = hex('#ffffff');
const C_LINE   = hex('#e2e8f0');

// ---------- drawing helpers ----------
function rgb(doc, arr) { doc.fillColor(arr); }

function drawHRule(doc, y, x1, x2, colorArr, thickness = 0.5) {
    doc.save()
       .strokeColor(colorArr)
       .lineWidth(thickness)
       .moveTo(x1, y)
       .lineTo(x2, y)
       .stroke()
       .restore();
}

function cell(doc, text, x, y, w, h, opts = {}) {
    const {
        fontSize = 9,
        fontColor = C_SLATE,
        bold = false,
        align = 'left',
        paddingX = 8,
        paddingY = 6,
        bg = null,
    } = opts;

    if (bg) {
        doc.save().rect(x, y, w, h).fillColor(bg).fill().restore();
    }

    doc.save()
       .font(bold ? 'Helvetica-Bold' : 'Helvetica')
       .fontSize(fontSize)
       .fillColor(fontColor)
       .text(String(text || ''), x + paddingX, y + paddingY, {
           width: w - paddingX * 2,
           height: h - paddingY * 2,
           align,
           ellipsis: true,
           lineBreak: false
       })
       .restore();
}

// ---------- header / footer ----------
function drawPageHeader(doc, pageNum) {
    if (pageNum === 1) return;
    doc.save()
       .font('Helvetica-Bold')
       .fontSize(10)
       .fillColor(C_LIGHT)
       .text('ASKURSENIOR', MARGIN, 22, { width: CONTENT_W, align: 'right' })
       .restore();
    drawHRule(doc, 40, MARGIN, PAGE_W - MARGIN, C_LINE);
}

function drawPageFooter(doc, pageNum, totalPages) {
    const y = PAGE_H - 28;
    drawHRule(doc, y - 6, MARGIN, PAGE_W - MARGIN, C_LINE);
    doc.save()
       .font('Helvetica')
       .fontSize(8)
       .fillColor(C_LIGHT)
       .text('Generated by AskUrSenior Admin Panel', MARGIN, y, { width: CONTENT_W / 2, align: 'left' })
       .text(`Page ${pageNum} of ${totalPages}`, MARGIN + CONTENT_W / 2, y, { width: CONTENT_W / 2, align: 'right' })
       .restore();
}

// ---------- main export ----------
exports.generateUsersReportPDF = (reportData) => {
    return new Promise((resolve, reject) => {
        try {
            const chunks = [];
            const doc = new PDFDocument({
                size: [PAGE_W, PAGE_H],   // landscape A4
                margins: { top: MARGIN, bottom: 15, left: MARGIN, right: MARGIN },
                autoFirstPage: false,
                bufferPages: true          // lets us go back and stamp page numbers
            });

            doc.on('data', c => chunks.push(c));
            doc.on('error', reject);
            doc.on('end', () => resolve(Buffer.concat(chunks)));

            const rangeStr = reportData.fromDate && reportData.toDate
                ? `${formatDate(reportData.fromDate)}  →  ${formatDate(reportData.toDate)}`
                : 'All Time';

            const mostRecent = (reportData.users || []).reduce((latest, u) => {
                if (!u.lastActiveAt) return latest;
                if (!latest || !latest.lastActiveAt) return u;
                return new Date(u.lastActiveAt) > new Date(latest.lastActiveAt) ? u : latest;
            }, null);
            const mostRecentStr = mostRecent
                ? `${mostRecent.name || 'Anonymous'}  (${formatDateTime(mostRecent.lastActiveAt)})`
                : 'N/A';

            // ==============================
            // PAGE 1 – COVER
            // ==============================
            doc.addPage();

            // Background top strip
            doc.save().rect(0, 0, PAGE_W, 220).fillColor(C_NAVY).fill().restore();

            // Title
            doc.save()
               .font('Helvetica-Bold')
               .fontSize(40)
               .fillColor(C_WHITE)
               .text('ASKURSENIOR', 0, 70, { width: PAGE_W, align: 'center' })
               .restore();

            doc.save()
               .font('Helvetica')
               .fontSize(16)
               .fillColor(C_LIGHT)
               .text('USERS REPORT', 0, 125, { width: PAGE_W, align: 'center' })
               .restore();

            // Info card
            const cardX = PAGE_W / 2 - 200;
            const cardY = 250;
            const cardW = 400;
            const ROW_H = 34;

            const infoRows = [
                ['Generated At',          formatDateTime(reportData.generatedAt)],
                ['Report Range',          rangeStr],
                ['Generated By',          'AskUrSenior Admin Panel'],
                ['Total Users In Report', String(reportData.summary.totalUsers || 0)],
            ];

            infoRows.forEach(([label, value], i) => {
                const ry = cardY + i * ROW_H;
                if (i % 2 === 0) {
                    doc.save().rect(cardX, ry, cardW, ROW_H).fillColor(C_ROW_A).fill().restore();
                } else {
                    doc.save().rect(cardX, ry, cardW, ROW_H).fillColor(C_WHITE).fill().restore();
                }
                doc.save()
                   .font('Helvetica-Bold')
                   .fontSize(9)
                   .fillColor(C_MUTED)
                   .text(label, cardX + 12, ry + 11, { width: 155, align: 'left' })
                   .restore();
                doc.save()
                   .font('Helvetica')
                   .fontSize(9)
                   .fillColor(C_SLATE)
                   .text(value, cardX + 170, ry + 11, { width: cardW - 182, align: 'left' })
                   .restore();
            });
            // card border
            doc.save()
               .rect(cardX, cardY, cardW, ROW_H * infoRows.length)
               .strokeColor(C_LINE)
               .lineWidth(1)
               .stroke()
               .restore();

            // SUMMARY section
            const sumY = cardY + ROW_H * infoRows.length + 40;

            doc.save()
               .font('Helvetica-Bold')
               .fontSize(12)
               .fillColor(C_NAVY)
               .text('SUMMARY', 0, sumY, { width: PAGE_W, align: 'center' })
               .restore();

            drawHRule(doc, sumY + 20, PAGE_W / 2 - 160, PAGE_W / 2 + 160, C_LINE);

            const sumRows = [
                ['Total Users',          String(reportData.summary.totalUsers || 0)],
                ['Most Recently Active', mostRecentStr],
                ['Avg Unique Tabs',      String(reportData.summary.averageTabsPerUser || 0)],
                ['Total Unique Tabs',    String(reportData.summary.totalUniqueTabsVisited || 0)],
            ];

            const sumX  = PAGE_W / 2 - 160;
            const sumW  = 320;
            const sROW  = 28;

            sumRows.forEach(([label, value], i) => {
                const ry = sumY + 30 + i * sROW;
                drawHRule(doc, ry + sROW, sumX, sumX + sumW, C_LINE, 0.4);
                doc.save()
                   .font('Helvetica')
                   .fontSize(9)
                   .fillColor(C_MUTED)
                   .text(label, sumX, ry + 8, { width: 140, align: 'left' })
                   .restore();
                doc.save()
                   .font('Helvetica-Bold')
                   .fontSize(9)
                   .fillColor(C_SLATE)
                   .text(value, sumX + 145, ry + 8, { width: sumW - 145, align: 'right' })
                   .restore();
            });

            drawPageFooter(doc, 1, 'X');

            // ==============================
            // PAGE 2+ – USER TABLE
            // ==============================
            const users = reportData.users || [];

            doc.addPage();
            drawPageHeader(doc, 2);

            // Table heading
            doc.save()
               .font('Helvetica-Bold')
               .fontSize(13)
               .fillColor(C_NAVY)
               .text('USER DETAILS', MARGIN, 50)
               .restore();

            drawHRule(doc, 70, MARGIN, PAGE_W - MARGIN, C_SLATE, 1);

            const TABLE_TOP   = 80;
            const DATA_ROW_H  = 28;
            const HEADER_H    = 32;

            // Column headers
            const HEADERS = ['Name', 'USN', 'Email', 'Joined Date & Time', 'Last Active Date & Time', 'Unique Tabs'];
            let cx = MARGIN;
            HEADERS.forEach((h, i) => {
                cell(doc, h, cx, TABLE_TOP, COL_WIDTHS[i], HEADER_H, {
                    fontSize: 9,
                    fontColor: C_WHITE,
                    bold: true,
                    bg: C_HEADER,
                    align: i === 5 ? 'right' : 'left',
                    paddingX: 8,
                    paddingY: 10,
                });
                cx += COL_WIDTHS[i];
            });

            if (users.length === 0) {
                doc.save()
                   .font('Helvetica')
                   .fontSize(13)
                   .fillColor(C_LIGHT)
                   .text('No users found for the selected date range.', MARGIN, TABLE_TOP + HEADER_H + 60, { width: CONTENT_W, align: 'center' })
                   .restore();
            } else {
                let currentY = TABLE_TOP + HEADER_H;
                let pageNum  = 2;

                users.forEach((u, idx) => {
                    // Start new page if near bottom
                    if (currentY + DATA_ROW_H > PAGE_H - 50) {
                        drawPageFooter(doc, pageNum, 'X');
                        pageNum++;
                        doc.addPage();
                        drawPageHeader(doc, pageNum);

                        // Repeat column headers on new page
                        cx = MARGIN;
                        HEADERS.forEach((h, i) => {
                            cell(doc, h, cx, 50, COL_WIDTHS[i], HEADER_H, {
                                fontSize: 9, fontColor: C_WHITE, bold: true,
                                bg: C_HEADER, align: i === 5 ? 'right' : 'left',
                                paddingX: 8, paddingY: 10,
                            });
                            cx += COL_WIDTHS[i];
                        });
                        currentY = 50 + HEADER_H;
                    }

                    const rowBg = idx % 2 === 0 ? C_ROW_A : C_WHITE;
                    const rowData = [
                        u.name || 'Anonymous',
                        u.usn || 'N/A',
                        u.email || '',
                        formatDateTime(u.createdAt),
                        formatDateTime(u.lastActiveAt),
                        String(u.uniqueTabsVisited || 0),
                    ];

                    cx = MARGIN;
                    rowData.forEach((val, i) => {
                        cell(doc, val, cx, currentY, COL_WIDTHS[i], DATA_ROW_H, {
                            fontSize: 8.5,
                            fontColor: i === 2 ? C_BLUE : C_SLATE,
                            bg: rowBg,
                            align: i === 5 ? 'right' : 'left',
                            paddingX: 8,
                            paddingY: 8,
                        });
                        cx += COL_WIDTHS[i];
                    });

                    drawHRule(doc, currentY + DATA_ROW_H, MARGIN, PAGE_W - MARGIN, C_LINE, 0.4);
                    currentY += DATA_ROW_H;
                });

                drawPageFooter(doc, pageNum, 'X');
            }

            // Go back and stamp real page count
            const range = doc.bufferedPageRange();
            const totalPages = range.count;
            for (let i = 0; i < totalPages; i++) {
                doc.switchToPage(range.start + i);
                // Overwrite footer page count by repainting background and re-drawing
                const fy = PAGE_H - 28;
                doc.save().rect(MARGIN + CONTENT_W / 2, fy - 2, CONTENT_W / 2, 18).fillColor(C_WHITE).fill().restore();
                doc.save()
                   .font('Helvetica')
                   .fontSize(8)
                   .fillColor(C_LIGHT)
                   .text(`Page ${i + 1} of ${totalPages}`, MARGIN + CONTENT_W / 2, fy, { width: CONTENT_W / 2, align: 'right' })
                   .restore();
            }

            doc.end();
        } catch (error) {
            reject(error);
        }
    });
};
