module.exports = {
    darkMode: 'class',
    content: [
        "./index.html",
        "./src/**/*.{js,jsx,ts,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                background: 'var(--background)',
                'background-secondary': 'var(--background-secondary)',
                surface: 'var(--surface)',
                'surface-secondary': 'var(--surface-secondary)',
                'surface-hover': 'var(--surface-hover)',
                'text-primary': 'var(--text-primary)',
                'text-secondary': 'var(--text-secondary)',
                'text-muted': 'var(--text-muted)',
                'text-faint': 'var(--text-faint)',
                border: 'var(--border)',
                'border-light': 'var(--border-light)',
                'border-focus': 'var(--border-focus)',
                card: 'var(--card-bg)',
                'card-border': 'var(--card-border)',
                navbar: 'var(--navbar-bg)',
                sidebar: 'var(--sidebar-bg)',
                input: 'var(--input-bg)',
                'input-border': 'var(--input-border)',
                primary: {
                    DEFAULT: 'var(--primary)',
                    hover: 'var(--primary-hover)',
                    surface: 'var(--primary-surface)',
                    border: 'var(--primary-border)',
                    50: '#f5f5f5',
                    100: '#e8e8e8',
                    200: '#d0d0d0',
                    500: '#8b5cf6',
                    600: '#7c3aed',
                    700: '#6d28d9',
                    800: '#1a1a1a',
                    900: '#000000',
                },
                secondary: {
                    500: '#ffffff',
                    600: '#f5f5f5',
                    700: '#e8e8e8',
                },
                success: {
                    DEFAULT: 'var(--success)',
                    surface: 'var(--success-surface)',
                },
                warning: {
                    DEFAULT: 'var(--warning)',
                    surface: 'var(--warning-surface)',
                },
                danger: {
                    DEFAULT: 'var(--danger)',
                    surface: 'var(--danger-surface)',
                },
                dark: {
                    50: '#2a2a2a',
                    100: '#1f1f1f',
                    200: '#1a1a1a',
                },
            },
        },
    },
    plugins: [],
};
