/**
 * Authoritative Static Dummy Data for Academic Overview Preview
 * Used for Non-Logged-in and Free (Non-Plus) users to showcase all platform states
 * without dispatching any backend/database requests.
 */
export const DUMMY_ACADEMIC_OVERVIEW = {
    semester: 3,
    scheme: 'Scheme 2025',
    student: {
        branch: 'CSE',
        usn: '1RV23CS042',
        name: 'Preview Student',
        cgpa: 8.18,
        currentSemester: 3,
    },
    availableSemesters: [1, 2, 3, 4],
    summary: {
        totalSubjects: 8,
        passedSubjects: 4,
        failedSubjects: 2,
        totalCreditsAttempted: 18.5,
        totalCreditsEarned: 9.5,
        sgpa: 8.42,
        cgpa: 8.18,
    },
    subjects: [
        {
            code: '21MAT31',
            name: 'Mathematics for Computer Science',
            credits: 3,
            category: 'Theory',
            pattern: 'Standard Theory',
            attendance: { percentage: 92, status: 'SATISFIED' },
            cie: { obtained: 43.0, max: 50 },
            see: { marks: 41, max: 50, enabled: true },
            aggregate: { marks: 84, max: 100 },
            eligibility: { eligible: true, reasons: [] },
            grade: { letter: 'A+', gradePoint: 9, description: 'Excellent' },
            contributesToSGPA: true,
        },
        {
            code: '21CS32',
            name: 'Data Structures and Applications',
            credits: 4,
            category: 'IPCC',
            pattern: 'Integrated Theory + Lab',
            attendance: { percentage: 88, status: 'SATISFIED' },
            cie: { obtained: 46.0, max: 50 },
            see: { marks: 45, max: 50, enabled: true },
            aggregate: { marks: 91, max: 100 },
            eligibility: { eligible: true, reasons: [] },
            grade: { letter: 'O', gradePoint: 10, description: 'Outstanding' },
            contributesToSGPA: true,
        },
        {
            code: '21CS33',
            name: 'Digital Design and Computer Organization',
            credits: 3,
            category: 'Theory',
            pattern: 'Standard Theory',
            attendance: { percentage: 73, status: 'SHORTAGE' },
            cie: { obtained: 32.0, max: 50 },
            see: { marks: null, max: 50, enabled: true },
            aggregate: { marks: null, max: 100 },
            eligibility: { eligible: false, reasons: ['Attendance below mandatory 85%'] },
            grade: { letter: null, gradePoint: null },
            contributesToSGPA: true,
        },
        {
            code: '21CS34',
            name: 'Operating Systems Principles',
            credits: 3,
            category: 'Theory',
            pattern: 'Standard Theory',
            attendance: { percentage: 86, status: 'SATISFIED' },
            cie: { obtained: 29.0, max: 50 },
            see: { marks: 17, max: 50, enabled: true },
            aggregate: { marks: 46, max: 100 },
            eligibility: { eligible: true, reasons: [] },
            grade: { letter: 'F', gradePoint: 0, description: 'Failed' },
            contributesToSGPA: true,
        },
        {
            code: '21CSL35',
            name: 'Data Structures Laboratory',
            credits: 1.5,
            category: 'Lab',
            pattern: 'Practical / Lab',
            attendance: { percentage: 96, status: 'SATISFIED' },
            cie: { obtained: 48.0, max: 50 },
            see: { marks: 47, max: 50, enabled: true },
            aggregate: { marks: 95, max: 100 },
            eligibility: { eligible: true, reasons: [] },
            grade: { letter: 'O', gradePoint: 10, description: 'Outstanding' },
            contributesToSGPA: true,
        },
        {
            code: '21CIP36',
            name: 'Constitution of India & Cyber Law',
            credits: 1,
            category: 'NCMC',
            pattern: 'Non-Credit Mandatory',
            attendance: { percentage: 91, status: 'SATISFIED' },
            cie: { obtained: 42.0, max: 50 },
            see: { marks: null, max: 0, enabled: false },
            aggregate: { marks: 84, max: 100 },
            eligibility: { eligible: true, reasons: [] },
            grade: { letter: 'PP', gradePoint: 0, description: 'Passed' },
            contributesToSGPA: false,
        },
        {
            code: '21EVS37',
            name: 'Environmental Studies',
            credits: 1,
            category: 'NCMC',
            pattern: 'Non-Credit Mandatory',
            attendance: { percentage: 65, status: 'SHORTAGE' },
            cie: { obtained: 18.0, max: 50 },
            see: { marks: null, max: 0, enabled: false },
            aggregate: { marks: 36, max: 100 },
            eligibility: { eligible: false, reasons: ['CIE below minimum requirement'] },
            grade: { letter: 'NP', gradePoint: 0, description: 'Not Passed' },
            contributesToSGPA: false,
        },
        {
            code: '21CS38',
            name: 'Full Stack Web Development',
            credits: 2,
            category: 'Elective',
            pattern: 'Elective Theory',
            attendance: { percentage: 89, status: 'SATISFIED' },
            cie: { obtained: 41.0, max: 50 },
            see: { marks: null, max: 50, enabled: true },
            aggregate: { marks: null, max: 100 },
            eligibility: { eligible: true, reasons: [] },
            grade: { letter: null, gradePoint: null },
            contributesToSGPA: true,
        },
    ]
};
