import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

// Watermark/logo removed for compatibility

export function generateResultAnalysisPDF(data) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // Header Section
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("RESULT ANALYSIS REPORT", pageWidth / 2, 50, { align: "center" });
  doc.setFontSize(12);
  doc.text(
    `Semester: ${data.student.semester}    Academic Year: ${data.student.year}    Generated On: ${new Date().toLocaleDateString()}`,
    pageWidth / 2,
    70,
    { align: "center" }
  );

  // Student Info
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text("------------------------------------------------------------", 40, 100);
  doc.text(`Student Name : ${data.student.name}`, 40, 115);
  doc.text(`USN          : ${data.student.usn}`, 40, 130);
  doc.text(`Program      : ${data.student.program || ""}`, 40, 145);
  doc.text("------------------------------------------------------------", 40, 160);

  let y = 180;

  // Subject-wise Analysis
  data.subjects.forEach((subj, idx) => {
    if (y > pageHeight - 200) {
      doc.addPage();
      y = 50;
    }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.text(`Subject: ${subj.name}`, 40, y);
    doc.setFontSize(11);
    doc.text(`Credits: ${subj.credits}    Type: ${subj.type}`, 40, y + 15);
    doc.text("--------------------------------------------------", 40, y + 30);

    doc.setFont("helvetica", "bold");
    doc.text("📘 CIE Breakdown", 40, y + 45);

    doc.setFont("helvetica", "normal");
    let lines = [];
    if (subj.type === "IPCC") {
      lines = [
        "CIE (Internal – 50 Marks)",
        `Theory (25 Marks)`,
        `Tests (T1+T2): ${subj.testsRaw} / 100`,
        `Quiz  (Q1+Q2): ${subj.quizRaw} / 40`,
        `ABL   (A1+A2): ${subj.ablRaw} / 40`,
        `Theory Contribution: ${subj.theoryValue} / 25`,
        "",
        `Practical (25 Marks)`,
        `Lab Records Total: ${subj.labRaw} / ${subj.labMax}`,
        `Lab Tests Total: ${subj.labTestRaw} / ${subj.labTestMax}`,
        `Practical Contribution: ${subj.practicalValue} / 25`,
        "",
        `Final CIE: ${subj.cieRounded} / 50`
      ];
    } else if (subj.type === "THEORY_ONLY") {
      lines = [
        `Theory Contribution: ${subj.cieRounded} / 50`,
        `Final CIE: ${subj.cieRounded} / 50`
      ];
    } else if (subj.type === "LAB_ONLY") {
      lines = [
        `Lab Contribution: ${subj.cieRounded} / 50`,
        `Final CIE: ${subj.cieRounded} / 50`
      ];
    }
    doc.setFontSize(11);
    doc.text(lines, 60, y + 65);

    // SEE & Final Result
    doc.setFont("helvetica", "bold");
    doc.text("📝 SEE & Final Result", 40, y + 180);
    doc.setFont("helvetica", "normal");
    doc.text(
      `SEE: ${subj.see} / 100  →  ${subj.see / 2} / 50\nFinal Marks: ${subj.finalMarks} / 100\nGrade: ${subj.grade}\nGrade Points: ${subj.gradePoints}\nStatus: ${subj.status}`,
      60,
      y + 200
    );

    doc.text("==================================================", 40, y + 260);
    y += 280;
  });

  // SGPA Summary
  if (y > pageHeight - 120) {
    doc.addPage();
    y = 50;
  }
  doc.setFont("helvetica", "bold");
  doc.text("SGPA SUMMARY", pageWidth / 2, y, { align: "center" });
  doc.setFont("helvetica", "normal");
  doc.text(
    `--------------------------------------------\nTotal Credits: ${data.totalCredits}\nTotal Grade Points: ${data.totalPoints}\nSGPA: ${data.sgpa}\n--------------------------------------------`,
    pageWidth / 2,
    y + 20,
    { align: "center" }
  );

  // Footer
  doc.setFontSize(9);
  doc.text(
    "• Minimum CIE required: 20\n• Minimum SEE required: 36\n• NE subjects carry 0 grade points\n--------------------------------------------------\nGenerated by Your Platform Name\n--------------------------------------------------",
    pageWidth / 2,
    pageHeight - 60,
    { align: "center" }
  );

  doc.save(`Result_Analysis_${data.student.usn}.pdf`);
}
